const ethers = require('ethers')

const encodeKey = (x) => ethers.utils.solidityKeccak256(['bytes32'], [toBytes32(x)])
const encodeKeys = (x, y) => ethers.utils.solidityKeccak256(x, y)
const toBytes32 = (x) => ethers.utils.formatBytes32String(x)
const getCoverContractKey = (namespace, coverKey) => encodeKeys(['bytes32', 'bytes32'], [toBytes32(namespace), coverKey])
const qualifyBytes32 = (k) => encodeKeys(['bytes32', 'bytes32'], [PROTOCOL.NS.CONTRACTS, k])
const qualify = (k) => encodeKeys(['bytes32', 'address'], [PROTOCOL.NS.CONTRACTS, k])
const qualifyMember = (k) => encodeKeys(['bytes32', 'address'], [PROTOCOL.NS.MEMBERS, k])

const ACCESS_CONTROL = {
  ADMIN: toBytes32(''),
  COVER_MANAGER: toBytes32('role:cover:manager'),
  LIQUIDITY_MANAGER: toBytes32('role:liquidity:manager'),
  GOVERNANCE_AGENT: toBytes32('role:governance:agent'),
  GOVERNANCE_ADMIN: toBytes32('role:governance:admin'),
  UPGRADE_AGENT: toBytes32('role:upgrade:agent'),
  RECOVERY_AGENT: toBytes32('role:recovery:agent'),
  PAUSE_AGENT: toBytes32('role:pause:agent'),
  UNPAUSE_AGENT: toBytes32('role:unpause:agent')
}

const BOND = {
  TO_CLAIM: toBytes32('ns:pool:bond:to:claim'),
  CONTRIBUTION: toBytes32('ns:pool:bond:contribution'),
  LP_TOKEN: toBytes32('ns:pool:bond:lq:pair:token'),
  DISCOUNT_RATE: toBytes32('ns:pool:bond:discount'),
  MAX_UNIT: toBytes32('ns:pool:bond:max:unit'),
  VESTING_TERM: toBytes32('ns:pool:bond:vesting:term'),
  UNLOCK_DATE: toBytes32('ns:pool:bond:unlock:date'),
  TOTAL_NPM_ALLOCATED: toBytes32('ns:pool:bond:total:npm:alloc'),
  TOTAL_NPM_DISTRIBUTED: toBytes32('ns:pool:bond:total:npm:distrib')
}

const PROTOCOL = {
  CNS: {
    CORE: toBytes32('cns:core'),
    NPM: toBytes32('cns:core:npm:instance'),
    COVER: toBytes32('cns:cover'),
    UNISWAP_V2_ROUTER: toBytes32('cns:core:uni:v2:router'),
    UNISWAP_V2_FACTORY: toBytes32('cns:core:uni:v2:factory'),
    PRICE_DISCOVERY: toBytes32('cns:core:price:discovery'),
    TREASURY: toBytes32('cns:core:treasury'),
    NPM_PRICE_ORACLE: toBytes32('cns:core:npm:price:oracle'),
    COVER_REASSURANCE: toBytes32('cns:cover:reassurance'),
    POOL_BOND: toBytes32('cns:pool:bond'),
    COVER_POLICY: toBytes32('cns:cover:policy'),
    COVER_POLICY_MANAGER: toBytes32('cns:cover:policy:manager'),
    COVER_POLICY_ADMIN: toBytes32('cns:cover:policy:admin'),
    COVER_STAKE: toBytes32('cns:cover:stake'),
    COVER_VAULT: toBytes32('cns:cover:vault'),
    COVER_VAULT_DELEGATE: toBytes32('cns:cover:vault:delegate'),
    COVER_STABLECOIN: toBytes32('cns:cover:sc'),
    COVER_CXTOKEN_FACTORY: toBytes32('cns:cover:cxtoken:factory'),
    COVER_VAULT_FACTORY: toBytes32('cns:cover:vault:factory'),
    BOND_POOL: toBytes32('cns:pools:bond'),
    STAKING_POOL: toBytes32('cns:pools:staking'),
    LIQUIDITY_ENGINE: toBytes32('cns:liquidity:engine'),
    STRATEGY_AAVE: toBytes32('cns:strategy:aave'),
    STRATEGY_COMPOUND: toBytes32('cns:strategy:compound'),
    GOVERNANCE: toBytes32('cns:gov'),
    GOVERNANCE_RESOLUTION: toBytes32('cns:gov:resolution'),
    CLAIM_PROCESSOR: toBytes32('cns:claim:processor'),
    BURNER: toBytes32('cns:core:burner')
  },
  NS: {
    MEMBERS: toBytes32('ns:members'),
    CONTRACTS: toBytes32('ns:contracts'),
    COVER: toBytes32('ns:cover'),
    COVER_PRODUCT: toBytes32('ns:cover:product'),
    COVER_PRODUCT_EFFICIENCY: toBytes32('ns:cover:product:efficiency'),
    COVER_CREATION_DATE: toBytes32('ns:cover:creation:date'),
    COVER_CREATION_FEE: toBytes32('ns:cover:creation:fee'),
    COVER_CREATION_MIN_STAKE: toBytes32('ns:cover:creation:min:stake'),
    COVER_REASSURANCE: toBytes32('ns:cover:reassurance'),
    COVER_REASSURANCE_PAYOUT: toBytes32('ns:cover:reassurance:payout'),
    COVER_REASSURANCE_WEIGHT: toBytes32('ns:cover:reassurance:weight'),
    COVER_REASSURANCE_RATE: toBytes32('ns:cover:reassurance:rate'),
    COVER_LEVERAGE_FACTOR: toBytes32('ns:cover:leverage:factor'),
    COVER_CREATION_FEE_EARNING: toBytes32('ns:cover:creation:fee:earning'),
    COVER_INFO: toBytes32('ns:cover:info'),
    COVER_OWNER: toBytes32('ns:cover:owner'),
    COVER_SUPPORTS_PRODUCTS: toBytes32('ns:cover:supports:products'),
    VAULT_STRATEGY_OUT: toBytes32('ns:vault:strategy:out'),
    VAULT_LENDING_INCOMES: toBytes32('ns:vault:lending:incomes'),
    VAULT_LENDING_LOSSES: toBytes32('ns:vault:lending:losses'),
    VAULT_DEPOSIT_HEIGHTS: toBytes32('ns:vault:deposit:heights'),
    COVER_LIQUIDITY_LENDING_PERIOD: toBytes32('ns:cover:liquidity:len:p'),
    COVER_LIQUIDITY_MAX_LENDING_RATIO: toBytes32('ns:cover:liquidity:max:lr'),
    COVER_LIQUIDITY_WITHDRAWAL_WINDOW: toBytes32('ns:cover:liquidity:ww'),
    COVER_LIQUIDITY_MIN_STAKE: toBytes32('ns:cover:liquidity:min:stake'),
    COVER_LIQUIDITY_STAKE: toBytes32('ns:cover:liquidity:stake'),
    COVER_LIQUIDITY_COMMITTED: toBytes32('ns:cover:liquidity:committed'),
    COVER_STABLECOIN_NAME: toBytes32('ns:cover:stablecoin:name'),
    COVER_REQUIRES_WHITELIST: toBytes32('ns:cover:requires:whitelist'),
    COVER_HAS_FLASH_LOAN: toBytes32('ns:cover:has:fl'),
    COVER_LIQUIDITY_FLASH_LOAN_FEE: toBytes32('ns:cover:liquidity:fl:fee'),
    COVER_LIQUIDITY_FLASH_LOAN_FEE_PROTOCOL: toBytes32('ns:proto:cover:liquidity:fl:fee'),
    COVERAGE_LAG: toBytes32('ns:coverage:lag'),
    COVER_POLICY_RATE_FLOOR: toBytes32('ns:cover:policy:rate:floor'),
    COVER_POLICY_RATE_CEILING: toBytes32('ns:cover:policy:rate:ceiling'),
    POLICY_DISABLED: toBytes32('ns:policy:disabled'),
    POLICY_LAST_PURCHASE_ID: toBytes32('ns:policy:last:purchase:id'),
    COVER_STAKE: toBytes32('ns:cover:stake'),
    COVER_STAKE_OWNED: toBytes32('ns:cover:stake:owned'),
    COVER_STATUS: toBytes32('ns:cover:status'),
    COVER_CXTOKEN: toBytes32('ns:cover:cxtoken'),
    VAULT_TOKEN_NAME: toBytes32('ns:vault:token:name'),
    VAULT_TOKEN_SYMBOL: toBytes32('ns:vault:token:symbol'),
    COVER_CREATOR_WHITELIST: toBytes32('ns:cover:creator:whitelist'),
    COVER_USER_WHITELIST: toBytes32('ns:cover:user:whitelist'),
    COVER_CLAIM_BLACKLIST: toBytes32('ns:cover:claim:blacklist'),
    GOVERNANCE_RESOLUTION_TS: toBytes32('ns:gov:resolution:ts'),
    GOVERNANCE_UNSTAKEN: toBytes32('ns:gov:unstaken'),
    GOVERNANCE_UNSTAKE_TS: toBytes32('ns:gov:unstake:ts'),
    GOVERNANCE_UNSTAKE_REWARD: toBytes32('ns:gov:unstake:reward'),
    GOVERNANCE_UNSTAKE_BURNED: toBytes32('ns:gov:unstake:burned'),
    GOVERNANCE_UNSTAKE_REPORTER_FEE: toBytes32('ns:gov:unstake:rep:fee'),
    GOVERNANCE_REPORTING_MIN_FIRST_STAKE: toBytes32('ns:gov:rep:min:first:stake'),
    GOVERNANCE_REPORTING_INCIDENT_DATE: toBytes32('ns:gov:rep:incident:date'),
    GOVERNANCE_REPORTING_PERIOD: toBytes32('ns:gov:rep:period'),
    GOVERNANCE_REPORTING_WITNESS_YES: toBytes32('ns:gov:rep:witness:yes'),
    GOVERNANCE_REPORTING_HAS_A_DISPUTE: toBytes32('ns:gov:rep:has:dispute'),
    GOVERNANCE_REPORTING_FINALIZATION: toBytes32('ns:gov:rep:has:finalized'),
    GOVERNANCE_REPORTING_WITNESS_NO: toBytes32('ns:gov:rep:witness:no'),
    GOVERNANCE_REPORTING_STAKE_OWNED_YES: toBytes32('ns:gov:rep:stake:owned:yes'),
    GOVERNANCE_REPORTING_STAKE_OWNED_NO: toBytes32('ns:gov:rep:stake:owned:no'),
    GOVERNANCE_REPORTING_BURN_RATE: toBytes32('ns:gov:rep:burn:rate'),
    GOVERNANCE_REPORTER_COMMISSION: toBytes32('ns:gov:reporter:commission'),
    CLAIM_PERIOD: toBytes32('ns:claim:period'),
    CLAIM_PAYOUTS: toBytes32('ns:claim:payouts'),
    CLAIM_BEGIN_TS: toBytes32('ns:claim:begin:ts'),
    CLAIM_EXPIRY_TS: toBytes32('ns:claim:expiry:ts'),
    RESOLUTION_DEADLINE: toBytes32('ns:resolution:deadline'),
    RESOLUTION_COOL_DOWN_PERIOD: toBytes32('ns:resolution:cdp'),
    COVER_PLATFORM_FEE: toBytes32('ns:cover:platform:fee'),
    CLAIM_REPORTER_COMMISSION: toBytes32('ns:claim:reporter:commission'),
    LAST_LIQUIDITY_STATE_UPDATE: toBytes32('ns:last:snl:update'),
    LIQUIDITY_STATE_UPDATE_INTERVAL: toBytes32('ns:snl:update:interval'),
    LENDING_STRATEGY_ACTIVE: toBytes32('ns:lending:strategy:active'),
    LENDING_STRATEGY_DISABLED: toBytes32('ns:lending:strategy:disabled'),
    LENDING_STRATEGY_WITHDRAWAL_START: toBytes32('ns:lending:strategy:w:start'),
    ACCRUAL_INVOCATION: toBytes32('ns:accrual:invocation'),
    LENDING_STRATEGY_WITHDRAWAL_END: toBytes32('ns:lending:strategy:w:end')
  },
  CNAME: {
    PROTOCOL: toBytes32('Neptune Mutual Protocol'),
    TREASURY: toBytes32('Treasury'),
    POLICY: toBytes32('Policy'),
    POLICY_ADMIN: toBytes32('Policy Admin'),
    BOND_POOL: toBytes32('BondPool'),
    STAKING_POOL: toBytes32('Staking Pool'),
    CLAIMS_PROCESSOR: toBytes32('Claims Processor'),
    COVER: toBytes32('Cover'),
    GOVERNANCE: toBytes32('Governance'),
    RESOLUTION: toBytes32('Resolution'),
    VAULT_FACTORY: toBytes32('Vault Factory'),
    CXTOKEN_FACTORY: toBytes32('cxToken Factory'),
    COVER_STAKE: toBytes32('Cover Stake'),
    COVER_REASSURANCE: toBytes32('Cover Reassurance'),
    LIQUIDITY_VAULT: toBytes32('Vault'),
    VAULT_DELEGATE: toBytes32('Vault Delegate'),
    LIQUIDITY_ENGINE: toBytes32('Liquidity Engine')
  }
}

const STAKING = {
  NAME: toBytes32('ns:pool:staking:name'),
  LOCKED: toBytes32('ns:pool:staking:locked'),
  LOCKUP_PERIOD_IN_BLOCKS: toBytes32('ns:pool:staking:lockup:period'),
  STAKING_TARGET: toBytes32('ns:pool:staking:target'),
  CUMULATIVE_STAKING_AMOUNT: toBytes32('ns:pool:staking:cum:amount'),
  STAKING_TOKEN: toBytes32('ns:pool:staking:token'),
  STAKING_TOKEN_UNI_STABLECOIN_PAIR: toBytes32('ns:pool:staking:token:uni:pair'),
  REWARD_TOKEN: toBytes32('ns:pool:reward:token'),
  REWARD_TOKEN_UNI_STABLECOIN_PAIR: toBytes32('ns:pool:reward:token:uni:pair'),
  STAKING_TOKEN_BALANCE: toBytes32('ns:pool:staking:token:balance'),
  REWARD_TOKEN_DEPOSITS: toBytes32('ns:pool:reward:token:deposits'),
  REWARD_TOKEN_DISTRIBUTION: toBytes32('ns:pool:reward:token:distrib'),
  MAX_STAKE: toBytes32('ns:pool:max:stake'),
  REWARD_PER_BLOCK: toBytes32('ns:pool:reward:per:block'),
  REWARD_PLATFORM_FEE: toBytes32('ns:pool:reward:platform:fee'),
  REWARD_TOKEN_BALANCE: toBytes32('ns:pool:reward:token:balance'),
  DEPOSIT_HEIGHTS: toBytes32('ns:pool:deposit:heights'),
  REWARD_HEIGHTS: toBytes32('ns:pool:reward:heights'),
  TOTAL_REWARD_GIVEN: toBytes32('ns:pool:reward:total:given')
}

module.exports = {
  encodeKey,
  encodeKeys,
  toBytes32,
  getCoverContractKey,
  qualify,
  qualifyMember,
  qualifyBytes32,
  ACCESS_CONTROL,
  BOND,
  PROTOCOL,
  STAKING
}
