const acl = require('./access-control')
const address = require('./address')
const erc20 = require('./erc-20')
const fraction = require('./fraction')
const initialization = require('./initialization')
const nonReentrancy = require('./non-reentrancy')
const notImplemented = require('./not-implemented')
const pausable = require('./pausable')
const revert = require('./revert')
const subtraction = require('./subtraction')
const todo = require('./todo')
const zero = require('./zero-value')
const accidentalZero = require('./accidental-zero')

module.exports = [acl, address, erc20, fraction, initialization, nonReentrancy, notImplemented, pausable, revert, subtraction, todo, zero, accidentalZero]
